// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, body, created_at, search_tsv
`

type CreateMessageParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RoomID, arg.UserID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.SearchTsv,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, user_id, body, created_at, search_tsv FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.SearchTsv,
	)
	return i, err
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT m.id, m.room_id, m.user_id, m.body, m.created_at, u.username
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.room_id = $1
  AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMessagesBeforeParams struct {
	RoomID    pgtype.UUID        `json:"room_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        pgtype.UUID        `json:"id"`
	Limit     int32              `json:"limit"`
}

type ListMessagesBeforeRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.RoomID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT m.id, m.room_id, m.user_id, m.body, m.created_at, u.username
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.room_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
}

type ListRecentMessagesRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMessagesRow{}
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.room_id, m.user_id, m.body, m.created_at, u.username
FROM messages m
JOIN users u ON u.id = m.user_id
JOIN room_members rm ON rm.room_id = m.room_id AND rm.user_id = $1
WHERE m.search_tsv @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(m.search_tsv, plainto_tsquery('english', $2)) DESC, m.created_at DESC
LIMIT 50
`

type SearchMessagesParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
}

type SearchMessagesRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.UserID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE room_members
SET last_read_message_id = $3
WHERE room_id = $1 AND user_id = $2
`

type UpdateLastReadParams struct {
	RoomID            pgtype.UUID `json:"room_id"`
	UserID            pgtype.UUID `json:"user_id"`
	LastReadMessageID pgtype.UUID `json:"last_read_message_id"`
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.RoomID, arg.UserID, arg.LastReadMessageID)
	return err
}
