// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SearchTsv interface{}        `json:"search_tsv"`
}

type Room struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	DmKey     *string            `json:"dm_key"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID            pgtype.UUID        `json:"room_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PublicKey    []byte             `json:"public_key"`
}
