// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	CreateDMRoom(ctx context.Context, arg CreateDMRoomParams) (Room, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDMByKey(ctx context.Context, dmKey *string) (Room, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error)
	ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error)
	ListRoomMemberIDs(ctx context.Context, roomID pgtype.UUID) ([]pgtype.UUID, error)
	ListRoomPeers(ctx context.Context, userID pgtype.UUID) ([]ListRoomPeersRow, error)
	ListRoomsForUser(ctx context.Context, userID pgtype.UUID) ([]ListRoomsForUserRow, error)
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	SetUserPublicKey(ctx context.Context, arg SetUserPublicKeyParams) error
	UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error
}

var _ Querier = (*Queries)(nil)
