// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createDMRoom = `-- name: CreateDMRoom :one
INSERT INTO rooms (name, kind, dm_key, created_by)
VALUES ('', 'dm', $1, $2)
RETURNING id, name, kind, dm_key, created_by, created_at
`

type CreateDMRoomParams struct {
	DmKey     *string     `json:"dm_key"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDMRoom(ctx context.Context, arg CreateDMRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createDMRoom, arg.DmKey, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, kind, created_by)
VALUES ($1, 'room', $2)
RETURNING id, name, kind, dm_key, created_by, created_at
`

type CreateRoomParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDMByKey = `-- name: GetDMByKey :one
SELECT id, name, kind, dm_key, created_by, created_at FROM rooms
WHERE dm_key = $1
`

func (q *Queries) GetDMByKey(ctx context.Context, dmKey *string) (Room, error) {
	row := q.db.QueryRow(ctx, getDMByKey, dmKey)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, kind, dm_key, created_by, created_at FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT id, name, kind, dm_key, created_by, created_at FROM rooms
WHERE kind = 'room' AND lower(name) = lower($1)
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetRoomByName(ctx context.Context, lower string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByName, lower)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DmKey,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS (
    SELECT 1 FROM room_members
    WHERE room_id = $1 AND user_id = $2
) AS is_member
`

type IsRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listPublicRooms = `-- name: ListPublicRooms :many
SELECT r.id, r.name
FROM rooms r
WHERE r.kind = 'room'
  AND NOT EXISTS (
    SELECT 1 FROM room_members rm
    WHERE rm.room_id = r.id AND rm.user_id = $1
  )
ORDER BY r.created_at
`

type ListPublicRoomsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListPublicRooms(ctx context.Context, userID pgtype.UUID) ([]ListPublicRoomsRow, error) {
	rows, err := q.db.Query(ctx, listPublicRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicRoomsRow{}
	for rows.Next() {
		var i ListPublicRoomsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMemberIDs = `-- name: ListRoomMemberIDs :many
SELECT user_id FROM room_members
WHERE room_id = $1
`

func (q *Queries) ListRoomMemberIDs(ctx context.Context, roomID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRoomMemberIDs, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPeers = `-- name: ListRoomPeers :many
SELECT DISTINCT u.id, u.username
FROM room_members me
JOIN room_members other ON other.room_id = me.room_id AND other.user_id <> me.user_id
JOIN users u ON u.id = other.user_id
WHERE me.user_id = $1
`

type ListRoomPeersRow struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
}

func (q *Queries) ListRoomPeers(ctx context.Context, userID pgtype.UUID) ([]ListRoomPeersRow, error) {
	rows, err := q.db.Query(ctx, listRoomPeers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomPeersRow{}
	for rows.Next() {
		var i ListRoomPeersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForUser = `-- name: ListRoomsForUser :many
SELECT
    r.id,
    r.kind,
    (CASE
        WHEN r.kind = 'dm' THEN COALESCE((
            SELECT u.username
            FROM room_members rm2
            JOIN users u ON u.id = rm2.user_id
            WHERE rm2.room_id = r.id AND rm2.user_id <> $1
            LIMIT 1
        ), 'dm')
        ELSE r.name
    END)::text AS display_name,
    (CASE WHEN r.kind = 'dm' THEN (
        SELECT rm3.user_id
        FROM room_members rm3
        WHERE rm3.room_id = r.id AND rm3.user_id <> $1
        LIMIT 1
    ) END)::uuid AS peer_id
FROM rooms r
JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
ORDER BY r.created_at
`

type ListRoomsForUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Kind        string      `json:"kind"`
	DisplayName string      `json:"display_name"`
	PeerID      pgtype.UUID `json:"peer_id"`
}

func (q *Queries) ListRoomsForUser(ctx context.Context, userID pgtype.UUID) ([]ListRoomsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRoomsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsForUserRow{}
	for rows.Next() {
		var i ListRoomsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DisplayName,
			&i.PeerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
